image: ruby:2.1

cache:
  paths:
    - vendor/

before_script:
  - bundle install --path vendor

# add a job called 'test'
test:
  stage: test
  script:
    - bundle exec jekyll build -d public/
  except:
    - stable

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public/
  artifacts:
    paths:
    - public
  only:
  - stable
