# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JL Best Practices
email: cihat.guenduez@jamitlabs.com
description: >
  Best practices for iOS and Android app development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/jamitlabs/BestPractices"
twitter_username: JamitLabs
github_username:  jamitlabs

# Build settings
markdown: kramdown
