# permalink:           pretty
# relative_permalinks: true

# Site settings
title:               Best Practices
tagline:             'Best practices for iOS and Android app development.'
description:         'Some best practices categorized by app development platform we are using at Jamit Labs.'
url:                 '' # the base hostname and protocol
email:               cihat.guenduez@jamitlabs.com
baseurl:             ''

# Build settings
markdown: kramdown

# Define new Categories here, order is respected when listing them in TOC
sections:
  General:
    - Version Control
  Apple:
    - Working with Xcode
  Android:
    - Test

collections:
  articles:
    output: true

defaults:
  - scope:
      path: "_articles"
      type: articles
    values:
      layout: article
