# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Define new Categories here, order is respected when listing them in TOC
sections:
  General:
    - Topic 1
  Apple:
    - Topic 2
  Android:
    - Topic 3
    - Topic 4
    - Topic 5
  # - "Apple"
  # - "Android"

# Define new topics per category here, order is respected when listing them in TOC
general_topics:
  - "V a"
  - "A v"
apple_topics:
  - "C b"
  - "B c"
android_topics:
  - "ab c"
  - "D e"
  - "E d"

collections:
  articles:
    output: true

defaults:
  - scope:
      path: "_articles"
      type: articles
    values:
      layout: article
