# permalink:           pretty
# relative_permalinks: true

# Site settings
title:               JL Best Practices
tagline:             'Best practices for iOS and Android app development.'
description:         'Some best practices categorized by app development platform we are using at Jamit Labs.'
url:                 https://github.com/jamitlabs/BestPractices
email:               cihat.guenduez@jamitlabs.com
baseurl:             ''
paginate:            5

twitter_username:    JamitLabs
github_username:     jamitlabs

# Custom vars
version:             1.0.0

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
